"""The discretionary layer, measured on real HMDA decisions.

    python run_overrides.py

HMDA records what the lender DECIDED. It does not record the score, the cutoff,
or whether anyone overrode anything -- no public mortgage dataset does, because
override logs are internal. So the honest construction is this:

  Fit a model on the underwriting variables HMDA does carry, calibrate its
  cutoff so it approves exactly as many applications as the market actually
  approved, and then look at the applications where the real decision and the
  model disagree.

WHAT THAT IS AND IS NOT. Those disagreements are **not observed overrides**.
They are decisions the underwriting variables in this file cannot explain, and
the largest single reason for that is the omitted variable the file does not
have: credit score. A real override log would separate "the underwriter used
information the model lacks" from "the model lacks information" -- this cannot,
and reading a disagreement rate here as an override rate would be exactly the
kind of inflated claim this project is written against.

WHAT SURVIVES ANYWAY, and it is the reason to run it. The model uses no
protected attribute. If the unexplained decisions were simply the credit score
the file is missing, they would land on applicants roughly in proportion to who
applies. Whether they actually do is measurable, and it is the fair-lending
question that matters: **a lender's model can be provably neutral and its
discretionary layer not be**, because the model is an equation and the override
is a person.

Writes docs/OVERRIDES.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.hmda import load, protected
from src.overrides import (Decision, discretion_disparity, effective_cutoff,
                           frame, override_report, override_value, undocumented)

FEATURES = ["dti", "ltv", "income_k", "loan_amount_k", "loan_to_income"]
PDO, BASE_SCORE, BASE_ODDS = 20.0, 620.0, 20.0


def _to_score(pd_bad: np.ndarray) -> np.ndarray:
    """Standard points-to-double-the-odds mapping, so the numbers read like a
    scorecard rather than a probability."""
    factor = PDO / np.log(2)
    offset = BASE_SCORE - factor * np.log(BASE_ODDS)
    odds_good = (1 - pd_bad) / np.clip(pd_bad, 1e-9, 1 - 1e-9)
    return offset + factor * np.log(np.clip(odds_good, 1e-9, None))


def main() -> int:
    if not (ROOT / "data" / "hmda_de_2023.csv").exists():
        print("data/hmda_de_2023.csv not found -- see src/hmda.py")
        return 1

    df = protected(load()).dropna(subset=FEATURES).copy()

    X = df[FEATURES].to_numpy(float)
    y = df.denied.to_numpy()
    model = LogisticRegression(max_iter=3000).fit(X, y)
    pd_bad = model.predict_proba(X)[:, 1]
    auc = roc_auc_score(y, pd_bad)
    df["score"] = _to_score(pd_bad)

    # Calibrate the cutoff so the MODEL approves exactly as many applications as
    # the market did. Any other cutoff would manufacture a one-sided disagreement
    # rate purely by being stricter or looser than reality, and the whole point
    # is to compare the shape of the two decisions rather than their volume.
    approval_rate = float((df.denied == 0).mean())
    cutoff = float(np.quantile(df.score, 1 - approval_rate))

    decisions = [
        Decision(app_id=str(i), score=float(r.score), cutoff=cutoff,
                 approved=bool(r.denied == 0),
                 group=str(r.race_group) if r.race_reported else "",
                 reason="", underwriter="")
        for i, r in enumerate(df.itertuples())
    ]
    d = frame(decisions)

    rep = override_report(d)
    eff = effective_cutoff(d)
    disp = discretion_disparity(d)

    L = []
    add = L.append
    add("# ML-3 — the discretionary layer, on real HMDA decisions")
    add("")
    add("Generated by `run_overrides.py` on {:,} real 2023 Delaware".format(len(df)))
    add("applications with complete underwriting fields.")
    add("")
    add("## 0. What is actually being measured, before any number")
    add("")
    add("HMDA records what the lender **decided**. It does not record the score,")
    add("the cutoff, or whether anyone overrode anything — no public mortgage")
    add("dataset does, because override logs are internal. So this fits a model")
    add("on the underwriting variables HMDA does carry, calibrates its cutoff so")
    add("it approves *exactly as many* applications as the market actually")
    add("approved, and examines the applications where the two disagree.")
    add("")
    add("**Those disagreements are not observed overrides.** They are decisions")
    add("the fields in this file cannot explain, and the largest single reason")
    add("for that is the variable the file does not have: credit score. A real")
    add("override log separates *the underwriter used information the model")
    add("lacks* from *the model lacks information*. This cannot, so the")
    add("disagreement rate below is an **upper bound on discretion** and reading")
    add("it as an override rate would be a false claim.")
    add("")

    add("## 1. The model standing in for policy")
    add("")
    add("| | |")
    add("|---|---|")
    add("| features | {} |".format(", ".join("`{}`".format(f) for f in FEATURES)))
    add("| AUC | {:.4f} |".format(auc))
    add("| market approval rate | {:.2%} |".format(approval_rate))
    add("| cutoff, calibrated to that rate | {:.1f} |".format(cutoff))
    add("")
    add("AUC {:.4f} is a weak model, and that is the honest starting point —".format(auc))
    add("without a credit score these five fields do not separate approvals from")
    add("denials well. Every disagreement number below inherits that weakness,")
    add("which is why the section above calls them an upper bound.")
    add("")

    add("## 2. How often the decision and the model disagree")
    add("")
    add("| | count | rate |")
    add("|---|---|---|")
    add("| approved below the model's cutoff (low-side) | {:,} | {:.2%} |".format(
        rep["low_side"], rep["low_side_rate"]))
    add("| declined above it (high-side) | {:,} | {:.2%} |".format(
        rep["high_side"], rep["high_side_rate"]))
    add("| total disagreement | {:,} | {:.2%} |".format(
        rep["low_side"] + rep["high_side"], rep["override_rate"]))
    add("")
    add("The two sides are equal by construction — the cutoff was calibrated to")
    add("match the market's approval volume, so every application waved in has")
    add("one turned away. That symmetry is a property of the calibration and")
    add("carries no information; the distribution of those decisions does.")
    add("")

    add("## 3. Where the line actually sits")
    add("")
    add("| | |")
    add("|---|---|")
    add("| policy cutoff | {:.1f} |".format(eff["policy_cutoff"]))
    add("| effective cutoff (lowest 10-point band still approving >=50%) | {:.1f} |".format(
        eff["effective_cutoff"]))
    add("| drift | {:+.1f} points |".format(eff["drift"]))
    add("| approval rate below the cutoff | {:.2%} |".format(
        eff["approval_rate_below_cutoff"]))
    add("| decline rate above it | {:.2%} |".format(eff["decline_rate_above_cutoff"]))
    add("")
    add("On a book following its own policy these two numbers are the same and")
    add("both rates are near zero. In a real deployment a gap means the model was")
    add("validated on a population the lender does not actually lend to.")
    add("")
    add("**Here it means something else, and the difference matters.** A drift of")
    add("{:+.0f} points is not evidence that Delaware lenders ignore their".format(
        eff["drift"]))
    add("policies — it is a restatement of the AUC in section 1. When the")
    add("stand-in model ranks applicants weakly, its score ordering and the real")
    add("decision ordering diverge everywhere, and the divergence shows up here")
    add("as drift. `src/overrides.py` flags sustained override rates above")
    add("{:.0%} because that is where a real policy stops describing a real".format(
        __import__("src.overrides", fromlist=["x"]).OVERRIDE_RATE_CONCERN))
    add("book; comparing the {:.2%} below against that threshold would be".format(
        rep["override_rate"]))
    add("comparing a model-fit statistic against a governance one.")
    add("")

    add("## 4. Is the unexplained layer evenly distributed?")
    add("")
    add("**This is the question worth asking of real data.** The model uses no")
    add("protected attribute. If the unexplained decisions were simply the")
    add("credit score this file is missing, they would fall on applicants")
    add("roughly in proportion to who applies.")
    add("")
    add("| group | decisions | waved in | turned away | **both** | low-side ratio | high-side ratio |")
    add("|---|---|---|---|---|---|---|")
    big = disp[disp.decisions >= 200].sort_values("low_side_rate",
                                                  ascending=False).copy()
    big["both"] = big.low_side_rate + big.high_side_rate
    for _, r in big.iterrows():
        add("| {} | {:,} | {:.2%} | {:.2%} | **{:.2%}** | {:.3f} | {:.3f} |".format(
            r.group, int(r.decisions), r.low_side_rate, r.high_side_rate,
            r.both, r.low_side_ratio, r.high_side_ratio))
    add("")
    add("Ratios are benchmarked against the best-treated group, matching the")
    add("80% rule in `src/fair_lending.py`: most favourable is most waved in and")
    add("least turned away.")
    add("")
    failing_low = big[big.low_side_ratio < 0.80]
    failing_high = big[big.high_side_ratio < 0.80]
    if len(failing_low) or len(failing_high):
        add("**{} of {} groups fall below 0.80 on being waved in, and {} on being".format(
            len(failing_low), len(big), len(failing_high)))
        add("turned away.** Under the 80% rule that is a screen failure in the")
        add("discretionary layer specifically — not in the model, which never saw")
        add("a protected attribute.")
    else:
        add("No group falls below 0.80 on either side. On this data the")
        add("unexplained decisions are distributed close to proportionally.")
    add("")
    add("**Read the `both` column before reading the ratios.** A group with")
    add("elevated disagreement in *both* directions is not obviously receiving")
    add("more discretion — it is a group the stand-in model fits worse. More")
    add("unexplained decisions in both directions is the signature of a")
    add("subpopulation whose approvals the five available fields predict poorly,")
    add("which is what the missing credit score would do if it is distributed")
    add("differently across groups. That is a materially different explanation")
    add("from discretion, it is not distinguishable in this data, and a one-sided")
    add("reading of the ratio columns would hide it.")
    add("")
    top = big.sort_values("both", ascending=False).iloc[0]
    bottom = big.sort_values("both").iloc[0]
    add("On this run the spread runs from **{:.2%}** ({}) to **{:.2%}** ({}) —".format(
        top.both, top.group, bottom.both, bottom.group))
    add("a factor of {:.1f}, and the group at the top has the *highest*".format(
        top.both / bottom.both if bottom.both else float("nan")))
    add("waved-in rate as well as a failing turned-away ratio. That pattern")
    add("fits worse model fit at least as well as it fits uneven discretion.")
    add("")
    add("The same caution as everywhere else in this project applies with full")
    add("force: this is every lender in the state pooled, the model is weak, and")
    add("the missing credit score is correlated with the protected attribute in")
    add("the population. A disparity here is a **screen result** — a reason to")
    add("pull the real override logs, which is a thing only the lender can do.")
    add("")

    # ---------------------------------------------- what cannot be done
    val = override_value(d)
    add("## 5. The question this data cannot answer at all")
    add("")
    add("Whether the discretion was *right*. That needs loan performance —")
    add("did the waved-in applications repay? — and HMDA has no outcome field.")
    add("`override_value` returns:")
    add("")
    add("> {}".format(val.get("note", val)))
    add("")
    add("and it returns that rather than a number, because a silent zero would")
    add("read as *overrides perform in line* when it means *there is nothing to")
    add("compare against*. Freddie Mac's Single-Family Loan-Level dataset is free")
    add("and does carry repayment outcomes, but it contains only **originated**")
    add("loans — no denials — so it can never identify an override either. The")
    add("two halves of the question live in two datasets and no public source")
    add("joins them.")
    add("")
    add("The counter-intuitive part, recorded because it is where this analysis")
    add("would go wrong next: overrides *outperforming* their benchmark is not")
    add("good news. It means the underwriters are using a real predictor the")
    add("model does not have, and the correct response is to find that feature")
    add("and retrain — not to widen the override policy.")
    add("")

    n_undoc = len(undocumented(d))
    add("## 6. What a real deployment records and this cannot")
    add("")
    add("| field | why it matters | in HMDA |")
    add("|---|---|---|")
    add("| the score at decision time | recomputing under a later model lets a recalibration retroactively rewrite override history | no |")
    add("| model version | same reason | no |")
    add("| override reason code | a high-side override with no reason is an adverse action without a documented basis — an ECOA problem before a modelling one | no |")
    add("| underwriter id | delegated authority concentrates; one person accounting for a third of low-side overrides is a control finding regardless of performance | no |")
    add("| loan outcome | the only way to know whether the discretion was right | no |")
    add("")
    add("All {:,} disagreements here are undocumented in the reason-code sense,".format(
        n_undoc))
    add("which is a property of the dataset rather than a finding about any")
    add("lender. `src/overrides.py` carries the checks; this file is a")
    add("demonstration of them against the most realistic input available for")
    add("free, and an explicit statement of what that input cannot support.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "OVERRIDES.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/OVERRIDES.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
