"""Assemble docs/SCORECARD_VALIDATION.md from measured numbers.

ML-1 ships a validation report; this project did not. The document is generated
rather than written, for the same reason ML-1's RESULTS.md is: a validation pack
whose numbers were typed in by the developer is a document about the developer's
memory.

    python run_validation_report.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from run_scorecard import (ALL_CHARACTERISTICS, APPROVAL_RATE, CATEGORICAL,
                           FEATURES, SPECIAL_VALUES, TARGET, _column)
from src import stability
from src.categorical import fit_categorical_binning, fit_hybrid_binning
from src.generate import generate
from src.scorecard import Scorecard, ScorecardConfig
from src.woe import fit_binning


def main() -> None:
    df = generate()
    funded = df[df.approved_by_incumbent == 1].reset_index(drop=True)
    cut = int(len(funded) * 0.7)
    tr, te = funded.iloc[:cut], funded.iloc[cut:]
    y_tr, y_te = tr[TARGET].to_numpy(), te[TARGET].to_numpy()

    binnings = {f: fit_binning(tr[f].to_numpy(float), y_tr, f) for f in FEATURES}
    for f in CATEGORICAL:
        binnings[f] = fit_categorical_binning(tr[f].to_numpy(object), y_tr, f)
    for f, sp in SPECIAL_VALUES.items():
        binnings[f] = fit_hybrid_binning(tr[f].to_numpy(float), y_tr, f, sp)

    card = Scorecard(binnings, ScorecardConfig()).fit(
        {f: _column(tr, f) for f in ALL_CHARACTERISTICS}, y_tr)
    X_te = {f: _column(te, f) for f in ALL_CHARACTERISTICS}
    p = card.predict_proba(X_te)
    s = card.scores(X_te)

    auc = float(roc_auc_score(y_te, p))
    fpr, tpr, _ = roc_curve(y_te, p)
    ks = float(np.max(tpr - fpr))
    brier = float(np.mean((p - y_te) ** 2))
    lo, hi, _ = stability.bootstrap_ci(
        lambda yy, pp: roc_auc_score(yy, pp), y_te, p, n_boot=400)

    v_te = te["vintage_month"].to_numpy()
    early, late = v_te <= 3, v_te >= 8
    pred_gap = float(p[late].mean() - p[early].mean())
    obs_gap = float(y_te[late].mean() - y_te[early].mean())
    char_psi = stability.characteristic_stability(
        np.column_stack([te[f].to_numpy(float) for f in FEATURES])[early],
        np.column_stack([te[f].to_numpy(float) for f in FEATURES])[late],
        FEATURES)

    L = []
    a = L.append
    a("# ML-3 -- scorecard validation report")
    a("")
    a("Generated by `run_validation_report.py`. Every number below is measured")
    a("on the run that produced this file. **Nothing here is signed** -- see §7.")
    a("")
    a("## 1. Model identification")
    a("")
    a("| | |")
    a("|---|---|")
    a("| Purpose | rank-order default risk on consumer instalment applications |")
    a("| Type | WoE binning + logistic regression, points-scaled |")
    a("| Scaling | base {:.0f} at {:.0f}:1 odds, PDO {:.0f} (factor {:.3f}, offset {:.3f}) |".format(
        card.cfg.base_score, card.cfg.base_odds, card.cfg.pdo,
        card.cfg.factor, card.cfg.offset))
    a("| Characteristics | {} numeric, {} categorical, {} hybrid |".format(
        len(FEATURES), len(CATEGORICAL), len(SPECIAL_VALUES)))
    a("| Build sample | {:,} funded applications |".format(len(tr)))
    a("| Validation sample | {:,} funded applications, held out |".format(len(te)))
    a("| Data | **synthetic** -- generated by `src/generate.py` |")
    a("")
    a("## 2. The limitation that governs every number below")
    a("")
    a("The data is generated by this repository. Every metric in this document")
    a("is a property of that generator, not of a lending population, and the")
    a("protected attribute used in the fair-lending section is a synthetic")
    a("overlay this repo constructs. **No result here is evidence the model")
    a("works on real applicants.** This section is second rather than last on")
    a("purpose.")
    a("")
    a("Beyond that: the model is fit on FUNDED loans only, while the scoring")
    a("population is all applicants. Funded default rate is {:.2%}; the true".format(
        funded[TARGET].mean()))
    a("all-applicant rate is {:.2%}, visible only because the generator".format(
        df[TARGET].mean()))
    a("produced it. Reject inference propagates an assumption about that gap; it")
    a("does not close it.")
    a("")
    a("## 3. Discrimination and calibration")
    a("")
    a("| metric | value |")
    a("|---|---|")
    a("| AUC | {:.4f} [{:.4f}, {:.4f}] (bootstrap 95%) |".format(auc, lo, hi))
    a("| Gini | {:.4f} |".format(2 * auc - 1))
    a("| KS | {:.4f} |".format(ks))
    a("| Brier | {:.5f} |".format(brier))
    a("| Score range (validation) | {:.0f} to {:.0f} |".format(s.min(), s.max()))
    a("")
    a("The interval is the number that matters. A point estimate of {:.4f}".format(auc))
    a("invites a comparison against a challenger that the sample cannot")
    a("support -- and `run_stability.py` shows exactly that trap: the individual")
    a("intervals of card and challenger overlap heavily, while a PAIRED")
    a("bootstrap excludes zero.")
    a("")
    a("## 4. Characteristic-level review")
    a("")
    a("| characteristic | kind | IV | bins |")
    a("|---|---|---|---|")
    for f in ALL_CHARACTERISTICS:
        kind = ("numeric" if f in FEATURES
                else "categorical" if f in CATEGORICAL else "hybrid")
        a("| {} | {} | {:.4f} | {} |".format(f, kind, binnings[f].iv,
                                             len(binnings[f].bins)))
    a("")
    a("Three treatments a reviewer should check, and what this card does:")
    a("")
    a("- **Missing is a LEVEL, not a hole.** `employment_type` is missing for")
    a("  {:.1%} of the build sample, and that missingness is not at random --".format(
        float(tr.employment_type.isna().mean())))
    a("  it concentrates in the self-employed, who default more. Imputing the")
    a("  mode imports the W2 default rate onto the riskiest slice of the book.")
    a("- **Special codes are not quantities.** `credit_age_reported` carries the")
    a("  bureau's -9 no-hit code. Binned as a number it sorts below every real")
    a("  credit age and inherits the youngest-file risk, which is an artefact of")
    a("  the encoding. It gets its own bin.")
    a("- **Rare levels are merged, not scored.** A level with a handful of")
    a("  accounts produces a WoE that is noise, and a card that assigns it")
    a("  points is assigning points to noise.")
    a("")
    a("## 5. Stability")
    a("")
    a("Characteristic PSI, early vintages (M00-M03) against late (M08-M11):")
    a("")
    a("| characteristic | PSI | band |")
    a("|---|---|---|")
    for row in char_psi:
        a("| {} | {:.4f} | {} |".format(
            row["characteristic"], row["psi"], row["band"]))
    a("")
    a("**And this is where a PSI-only monitoring pack fails.** Over the same")
    a("span the actual default rate moved **{:+.2%}**, of which the model".format(obs_gap))
    a("predicted **{:+.2%}** -- leaving **{:+.2%} unexplained**. PSI found the".format(
        pred_gap, obs_gap - pred_gap))
    a("mix shift it is designed to find, and the mix shift is the smaller half.")
    a("Applicants defaulting more AT THE SAME characteristics is invisible to")
    a("any distribution statistic on those characteristics, by construction.")
    a("")
    a("Monitoring plan implied by that: PSI is a supporting signal, and the")
    a("primary one is the vintage actual-versus-expected gap, which needs")
    a("outcomes and is therefore months late. There is no early label-free")
    a("signal for outcome shift, and pretending PSI is one is the error this")
    a("section exists to prevent.")
    a("")
    a("## 6. Use limitations")
    a("")
    a("- Rank-ordering only. The PDs are calibrated on the funded population and")
    a("  must not be used to price the rejected one.")
    a("- No override policy, no manual-underwrite path, no low-side/high-side")
    a("  override tracking.")
    a("- The approval cutoff ({:.0%} approval rate) is a policy input, not a".format(
        APPROVAL_RATE))
    a("  model output, and belongs to credit policy rather than to modelling.")
    a("")
    a("## 7. Sign-off")
    a("")
    a("| role | name | date |")
    a("|---|---|---|")
    a("| Developer | (this repository) | generated |")
    a("| Independent validator | **UNSIGNED** | -- |")
    a("| Credit policy owner | **UNSIGNED** | -- |")
    a("")
    a("Developer and validator are the same party. Under SR 11-7 that alone")
    a("blocks production use, and no further writing fixes it. The row is left")
    a("as UNSIGNED rather than removed, because a validation pack without a")
    a("sign-off section reads as though one was never required.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "SCORECARD_VALIDATION.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/SCORECARD_VALIDATION.md")


if __name__ == "__main__":
    main()
