"""Fair-lending analysis -> docs/FAIR_LENDING.md.

Separate from run_scorecard.py because the audiences differ: that script is a
modelling report, this one is the document a compliance reviewer reads.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from run_scorecard import APPROVAL_RATE, FEATURES, TARGET
from src import fair_lending as fl
from src.generate import generate
from src.scorecard import Scorecard, ScorecardConfig
from src.woe import fit_binning

PROXIES = ["region_risk_proxy_a", "region_risk_proxy_b"]


def add_proxy_features(df):
    """Two features that a lender would plausibly use and that partially encode
    geography -- the realistic form of the proxy problem. Neither is the
    protected attribute; both correlate with it through region_risk.

    This is how proxies actually arrive: nobody adds `race`. Somebody adds a
    branch-distance feature and a local-delinquency-index feature, each with a
    perfectly good business rationale.
    """
    df = df.copy()
    rng = np.random.default_rng(4)
    df["region_risk_proxy_a"] = (df.region_risk * 100 + rng.normal(0, 6, len(df))).round(2)
    df["region_risk_proxy_b"] = (df.region_risk * 40 + df.utilization * 0.15
                                 + rng.normal(0, 4, len(df))).round(2)
    return df


def scorecard_fit_predict(X_tr, y_tr, X_te, names):
    cols = {n: X_tr[:, i] for i, n in enumerate(names)}
    binnings = {n: fit_binning(cols[n], y_tr, n) for n in names}
    card = Scorecard(binnings, ScorecardConfig())
    card.fit(cols, y_tr)
    return card.predict_proba({n: X_te[:, i] for i, n in enumerate(names)})


def main() -> None:
    df = add_proxy_features(generate())
    funded = df[df.approved_by_incumbent == 1].reset_index(drop=True)
    split = int(len(funded) * 0.7)
    tr, te = funded.iloc[:split], funded.iloc[split:]

    feats = FEATURES + PROXIES
    X_tr, y_tr = tr[feats].to_numpy(float), tr[TARGET].to_numpy()
    X_te, y_te = te[feats].to_numpy(float), te[TARGET].to_numpy()
    grp = te.protected_group_synthetic.to_numpy()

    L = []
    L.append("# Fair Lending Analysis\n")
    L.append("> **The protected attribute in this document is SYNTHETIC.** It is "
             "generated by `src/generate.py` and correlated with `region_risk` by "
             "construction, so that a genuine proxy structure exists to detect. "
             "Every ratio below is a property of that construction. Nothing here "
             "describes a real population, and presenting these as findings about "
             "one would be exactly the control failure this repository is written "
             "to avoid.\n")

    L.append("## Regulatory frame\n")
    L.append("ECOA / Regulation B (15 U.S.C. 1691; 12 CFR 1002) governs "
             "discrimination in credit. Reg B 1002.9 requires an adverse-action "
             "notice stating the **principal reasons** for a denial -- which is why "
             "the points-lost reason codes in `src/scorecard.py` are a regulatory "
             "artifact rather than a modelling nicety.\n")
    L.append("- **Disparate treatment**: using a prohibited basis as an input, or "
             "treating applicants differently because of it. Neither model here "
             "takes the attribute as an input, so treatment is not the question.\n"
             "- **Disparate impact**: a facially neutral policy that "
             "disproportionately burdens a protected class, is not justified by "
             "business necessity, **or** for which a less discriminatory "
             "alternative exists that serves the same purpose. That final clause "
             "is analysed in section 5; it is the one most analyses omit.\n")

    # ---- 1. AIR with a confidence interval --------------------------------
    def fp_card(a, b, c, names=None):
        return scorecard_fit_predict(a, b, c, names or feats)

    s_card = fp_card(X_tr, y_tr, X_te)
    thr = float(np.quantile(s_card, APPROVAL_RATE))
    approved = s_card <= thr
    air = fl.adverse_impact_ratio(approved, grp)
    lo, hi = fl.air_confidence_interval(approved, grp)

    L.append("\n## 1. Adverse impact ratio at a {:.0%} approval rate\n".format(APPROVAL_RATE))
    L.append("| group | n | approval rate |\n|---|---|---|")
    L.append("| 1 | {:,} | {:.4f} |".format(int((grp == 1).sum()), air["rate_1"]))
    L.append("| 0 | {:,} | {:.4f} |".format(int((grp == 0).sum()), air["rate_0"]))
    L.append("\n**AIR = {:.4f}**, bootstrap 95% CI [{:.4f}, {:.4f}] -> {}\n".format(
        air["air"], lo, hi,
        "**FLAGS the 80% rule**" if air["flags"] else "does not flag the 80% rule"))
    L.append("The interval is reported because the 80% rule gets applied to a point "
             "estimate as though it were exact. An AIR of 0.79 on a thin sample and "
             "0.79 on a fat one are not the same finding.\n")

    # ---- 2. score distribution --------------------------------------------
    sd = fl.score_distribution(s_card, grp)
    L.append("\n## 2. Score distribution across groups\n")
    L.append("| statistic | group 1 | group 0 |\n|---|---|---|")
    L.append("| mean PD | {:.4f} | {:.4f} |".format(sd["mean_1"], sd["mean_0"]))
    L.append("| median PD | {:.4f} | {:.4f} |".format(sd["median_1"], sd["median_0"]))
    L.append("| 10th pct PD | {:.4f} | {:.4f} |".format(sd["p10_1"], sd["p10_0"]))
    L.append("\nGroup-separation AUC of the score: **{:.4f}** (0.500 = "
             "indistinguishable).\n".format(sd["separation_auc"]))

    # ---- 3. proxy reconstruction ------------------------------------------
    recon = fl.proxy_reconstruction(X_te, grp)
    L.append("\n## 3. Can the model's features reconstruct the protected attribute?\n")
    L.append("Probe: logistic regression from the model's own features to group "
             "membership. **AUC = {:.4f}**.\n".format(recon))
    L.append("This is the number that decides whether \"we do not use the "
             "attribute\" means anything. At 0.5 the features carry no group "
             "information; materially above it, the model can act on the attribute "
             "without ever being shown it.\n")

    # ---- 4. proxy ablation ------------------------------------------------
    L.append("\n## 4. Proxy ablation\n")
    L.append("Suspected proxies: `{}` -- two features with ordinary business "
             "rationales (a regional risk index and a blended geography/utilisation "
             "score) that partially encode geography. This is how proxies actually "
             "arrive: nobody adds a prohibited basis, somebody adds a "
             "branch-distance feature.\n".format("`, `".join(PROXIES)))

    abl = fl.proxy_ablation(fp_card, X_tr, y_tr, X_te, feats, grp, PROXIES,
                            APPROVAL_RATE)
    L.append("| | full model | proxies dropped | change |\n|---|---|---|---|")
    L.append("| AIR | {:.4f} | {:.4f} | {:+.4f} |".format(
        abl["air_full"], abl["air_ablated"], abl["air_change"]))
    L.append("| group reconstruction AUC | {:.4f} | {:.4f} | {:+.4f} |".format(
        abl["recon_full"], abl["recon_ablated"],
        abl["recon_ablated"] - abl["recon_full"]))
    L.append("\n**{:.0%} of the recoverable group signal survives** dropping both "
             "proxies.\n".format(abl["signal_retained"]))

    if abs(abl["air_change"]) < 0.01 and abl["recon_ablated"] < abl["recon_full"] - 0.02:
        L.append("This is the uncomfortable result, and it is the common one: "
                 "reconstruction fell (the dropped columns really did carry group "
                 "information) while the disparity did **not** move. The columns "
                 "were not the cause of the impact. Dropping them costs "
                 "discrimination and buys no fairness -- a cosmetic change that "
                 "looks like remediation in a slide and is not one. Reporting only "
                 "the reconstruction number would have made this look like a "
                 "success.\n")
    elif abl["air_change"] > 0.01:
        L.append("Dropping the proxies materially improved the AIR, which makes "
                 "them a genuine driver of the disparity and a live remediation "
                 "candidate -- weighed against the discrimination lost.\n")
    else:
        L.append("Neither the disparity nor the reconstruction moved materially; "
                 "the proxies are not the mechanism here.\n")

    # ---- 5. less discriminatory alternative --------------------------------
    L.append("\n## 5. Less-discriminatory-alternative search\n")
    gbm_auc, gbm_air = _gbm_candidate(X_tr, y_tr, X_te, y_te, grp)
    card_auc = float(roc_auc_score(y_te, s_card))
    abl_auc = float(roc_auc_score(y_te, abl["scores_ablated"]))
    candidates = {
        "champion": {"air": abl["air_full"], "auc": card_auc},
        "scorecard_without_proxies": {"air": abl["air_ablated"], "auc": abl_auc},
        "gbm_challenger": {"air": gbm_air, "auc": gbm_auc},
    }
    lda = fl.less_discriminatory_alternative_search(candidates)
    L.append("Tolerance (a stated policy choice, not a discovered constant): an "
             "alternative qualifies if it raises AIR by >= {:.2f} while giving up "
             "<= {:.3f} AUC.\n".format(lda["air_min_gain"], lda["auc_tolerance"]))
    L.append("| candidate | AUC | AIR | AIR gain | AUC cost | verdict |")
    L.append("|---|---|---|---|---|---|")
    L.append("| champion (scorecard, all features) | {:.4f} | {:.4f} | - | - | baseline |"
             .format(candidates["champion"]["auc"], candidates["champion"]["air"]))
    for a in lda["assessed"]:
        c = candidates[a["name"]]
        L.append("| {} | {:.4f} | {:.4f} | {:+.4f} | {:+.4f} | {} |".format(
            a["name"], c["auc"], c["air"], a["air_gain"], a["auc_cost"],
            a["verdict"]))
    if lda["blocked_on_cost"]:
        b = lda["blocked_on_cost"][0]
        L.append("\n**This is the interesting outcome, so it should not be read past.** "
                 "`{}` reduces the disparity by {:+.4f} AIR at a cost of {:.4f} AUC. "
                 "The stated tolerance is {:.3f}, so under the policy as written it "
                 "does not qualify -- but the policy is a number I chose, and a "
                 "regulator's question would be why {:.3f} rather than {:.4f}. "
                 "Answering \"our tolerance said no\" is not a defence when the "
                 "tolerance was set by the party whose model is under review. The "
                 "honest position is that this alternative is live and the tolerance "
                 "needs an owner outside modelling.\n".format(
                     b["name"], b["air_gain"], b["auc_cost"],
                     lda["auc_tolerance"], lda["auc_tolerance"], b["auc_cost"]))
    L.append("\n**Conclusion: {}.**\n".format(lda["conclusion"]))
    L.append("Showing business necessity does not end a disparate-impact analysis. "
             "If a less discriminatory alternative serves the same purpose "
             "comparably well, the original practice remains actionable -- so the "
             "search has to be run and recorded even when it comes back empty.\n")

    # ---- 6. limitations ----------------------------------------------------
    L.append("\n## 6. What this analysis does NOT establish\n")
    L.append("- **Nothing about any real population.** The attribute is synthetic.\n"
             "- No causal mechanism. AIR is an outcome ratio.\n"
             "- No business-necessity documentation for the features that drive the "
             "disparity -- that requires the lender's own justification, not the "
             "modeller's.\n"
             "- One binary attribute. No intersectional analysis, no age or marital "
             "status, no geography-based redlining analysis.\n"
             "- Training population is funded loans only, so the disparity measured "
             "is conditional on the incumbent's approval policy, which itself may "
             "carry impact this analysis cannot see. See reject inference in the "
             "README.\n")

    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "FAIR_LENDING.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    print("AIR {:.4f} CI [{:.4f}, {:.4f}]  reconstruction AUC {:.4f}".format(
        air["air"], lo, hi, recon))
    print("ablation: AIR {:+.4f}, signal retained {:.0%}".format(
        abl["air_change"], abl["signal_retained"]))
    print("LDA search: {}".format(lda["conclusion"]))
    print("wrote docs/FAIR_LENDING.md")


def _gbm_candidate(X_tr, y_tr, X_te, y_te, grp):
    m = HistGradientBoostingClassifier(max_iter=250, learning_rate=0.06,
                                       max_leaf_nodes=15, min_samples_leaf=100,
                                       random_state=0)
    m.fit(X_tr, y_tr)
    s = m.predict_proba(X_te)[:, 1]
    thr = float(np.quantile(s, APPROVAL_RATE))
    return float(roc_auc_score(y_te, s)), fl.adverse_impact_ratio(s <= thr, grp)["air"]


if __name__ == "__main__":
    main()
