"""Geographic disparity on real HMDA data, and why it is the hardest test to read.

    python run_redlining.py

Redlining analysis asks a different question from the AIR. The AIR asks whether
individual applicants of one group fare worse. Redlining asks whether **places**
do -- and the two come apart, because a lender can treat every applicant
identically and still decline a neighbourhood by not lending in it.

HMDA carries `census_tract`, and the CFPB publishes tract-level demographics, so
this is measurable on the data already downloaded. Writes docs/REDLINING.md.

THE THREE WAYS THIS ANALYSIS GOES WRONG, all of which this tries to avoid:

  THIN TRACTS       a tract with four applications and one denial has a 25%
                    denial rate and means nothing. Ranking on it puts noise at
                    the top of the report, which is where the reader looks.

  THE ECOLOGICAL    a tract-level correlation is not a statement about any
  FALLACY           individual in it. "Denial rates are higher in
                    majority-minority tracts" and "minority applicants are
                    denied more" are different claims with different evidence,
                    and conflating them is the standard error in this genre.

  THE OMITTED       tract demographics correlate with tract INCOME and with
  VARIABLE          property values. A disparity that survives no controls at
                    all is not evidence of redlining; it is evidence that
                    poorer areas get declined more, which everyone already
                    knows and which is not by itself unlawful.

So this reports the raw geography, then controls for what the file has, and is
explicit that what remains is a screen rather than a finding.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.hmda import load, protected

MIN_TRACT_APPLICATIONS = 30
FEATURES = ["dti", "ltv", "income_k", "loan_amount_k", "loan_to_income"]


def main() -> int:
    if not (ROOT / "data" / "hmda_de_2023.csv").exists():
        print("data/hmda_de_2023.csv not found -- see src/hmda.py")
        return 1

    df = protected(load())
    df = df[df.census_tract.notna()].copy()
    df["census_tract"] = df.census_tract.astype(str)

    L = []
    add = L.append
    add("# ML-3 — geographic disparity (redlining screen), HMDA 2023 Delaware")
    add("")
    add("Generated by `run_redlining.py`. **A different question from the AIR:**")
    add("the AIR asks whether individual applicants of one group fare worse;")
    add("this asks whether *places* do. They come apart — a lender can treat")
    add("every applicant identically and still decline a neighbourhood by not")
    add("lending in it.")
    add("")

    # ------------------------------------------------------- tract table
    g = df.groupby("census_tract").agg(
        applications=("denied", "size"),
        denials=("denied", "sum"),
        minority_share=("is_minority", "mean"),
        median_income_k=("income_k", "median"))
    g["denial_rate"] = g.denials / g.applications

    thin = g[g.applications < MIN_TRACT_APPLICATIONS]
    thick = g[g.applications >= MIN_TRACT_APPLICATIONS].copy()

    add("## 1. Tracts, and the ones this refuses to rank")
    add("")
    add("| | |")
    add("|---|---|")
    add("| tracts in the file | {:,} |".format(len(g)))
    add("| tracts with >= {} applications | {:,} |".format(
        MIN_TRACT_APPLICATIONS, len(thick)))
    add("| tracts excluded as too thin | {:,} ({:.1%} of tracts, {:.1%} of applications) |".format(
        len(thin), len(thin) / len(g), thin.applications.sum() / g.applications.sum()))
    add("")
    add("A tract with four applications and one denial has a 25% denial rate and")
    add("means nothing. Ranking on it puts noise at the top of the report, which")
    add("is exactly where the reader looks — so thin tracts are excluded and the")
    add("**exclusion is reported**, because dropping {:.1%} of applications".format(
        thin.applications.sum() / g.applications.sum()))
    add("silently would be choosing the sample after seeing it.")
    add("")

    # -------------------------------------------------- minority-share bands
    add("## 2. Denial rate by tract minority share")
    add("")
    bands = pd.cut(thick.minority_share, [0, 0.2, 0.5, 0.8, 1.0],
                   include_lowest=True,
                   labels=["<20%", "20-50%", "50-80%", ">80%"])
    by_band = thick.groupby(bands, observed=True).agg(
        tracts=("applications", "size"),
        applications=("applications", "sum"),
        denials=("denials", "sum"),
        median_income_k=("median_income_k", "median"))
    by_band["denial_rate"] = by_band.denials / by_band.applications

    add("| tract minority share | tracts | applications | denial rate | median income |")
    add("|---|---|---|---|---|")
    for band, r in by_band.iterrows():
        add("| {} | {:,} | {:,} | {:.2%} | ${:,.0f}k |".format(
            band, int(r.tracts), int(r.applications), r.denial_rate,
            r.median_income_k))
    add("")

    rates = by_band.denial_rate.dropna()
    if len(rates) >= 2:
        spread = rates.max() - rates.min()
        add("Spread between the highest and lowest band: **{:.1f} percentage".format(
            spread * 100))
        add("points**.")
        add("")
        add("**And look at the income column before reading anything into that.**")
        add("Tract minority share correlates with tract income, so a raw")
        add("geographic gradient is partly an income gradient. A disparity that")
        add("survives no controls at all is not evidence of redlining — it is")
        add("evidence that poorer areas get declined more, which everyone")
        add("already knows and which is not by itself unlawful.")
    add("")

    # ------------------------------------------------- controlled screen
    add("## 3. Does tract composition still predict denial after controls?")
    add("")
    work = df.dropna(subset=FEATURES).copy()
    tract_share = thick.minority_share.to_dict()
    work["tract_minority_share"] = work.census_tract.map(tract_share)
    work = work.dropna(subset=["tract_minority_share"])

    X = work[FEATURES].to_numpy(float)
    y = work.denied.to_numpy()
    base = LogisticRegression(max_iter=3000).fit(X, y)
    auc_base = roc_auc_score(y, base.predict_proba(X)[:, 1])

    # The applicant's OWN group goes in first. Otherwise the tract coefficient
    # absorbs individual-level disparity and gets reported as geography, which
    # is the ecological fallacy with a regression in front of it.
    Xi = np.column_stack([X, work.is_minority.to_numpy().astype(int)])
    with_ind = LogisticRegression(max_iter=3000).fit(Xi, y)
    auc_ind = roc_auc_score(y, with_ind.predict_proba(Xi)[:, 1])

    Xt = np.column_stack([Xi, work.tract_minority_share.to_numpy(float)])
    with_tract = LogisticRegression(max_iter=3000).fit(Xt, y)
    auc_tract = roc_auc_score(y, with_tract.predict_proba(Xt)[:, 1])
    coef_ind = float(with_tract.coef_[0][-2])
    coef_tract = float(with_tract.coef_[0][-1])

    add("| model | AUC |")
    add("|---|---|")
    add("| underwriting only | {:.4f} |".format(auc_base))
    add("| + applicant's own group | {:.4f} |".format(auc_ind))
    add("| + tract minority share | {:.4f} |".format(auc_tract))
    add("")
    add("With both in the model:")
    add("")
    add("| term | coefficient | odds ratio |")
    add("|---|---|---|")
    add("| applicant is minority | {:+.4f} | {:.3f} |".format(
        coef_ind, np.exp(coef_ind)))
    add("| tract minority share | {:+.4f} | {:.3f} |".format(
        coef_tract, np.exp(coef_tract)))
    add("")
    add("**The applicant's own group is in the model first, on purpose.**")
    add("Without it the tract term absorbs individual-level disparity and gets")
    add("reported as geography — which is the ecological fallacy with a")
    add("regression in front of it.")
    add("")
    if abs(coef_tract) < 0.10:
        add("The tract term is close to zero once the applicant's own")
        add("characteristics and group are controlled. On this data the")
        add("geographic gradient is largely explained by who is applying from")
        add("where, rather than by where they are applying from.")
    else:
        add("The tract term survives. That is a **screen result**: after")
        add("controlling for the applicant's own underwriting profile AND their")
        add("own group, the composition of the neighbourhood still moves the")
        add("odds of denial by {:.1%}.".format(abs(np.exp(coef_tract) - 1)))
        add("")
        add("It is not a finding of redlining, and the reasons are the same as")
        add("everywhere else in this project: no credit score, no property")
        add("condition, no loan officer, and this is every lender in the state")
        add("pooled rather than one institution's conduct.")
    add("")

    add("## 4. What this still is not")
    add("")
    add("- **Not one lender.** Redlining is an institution's conduct. This pools")
    add("  every filer in the state, so it can identify a market pattern and")
    add("  cannot attribute it.")
    add("- **No application-rate denominator.** The strongest redlining evidence")
    add("  is not the denial rate in a tract — it is the near-absence of")
    add("  applications from it, which means measuring marketing and branch")
    add("  presence against tract population. HMDA alone cannot see that.")
    add("- **No peer comparison.** The standard method compares one lender")
    add("  against similarly situated peers in the same geography, and that")
    add("  needs a peer-group definition this does not have.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "REDLINING.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/REDLINING.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
