"""A scorecard fitted on repayment, and the fairness question HMDA could not ask.

    python run_repayment.py

Every card in this project has been fitted against `denied` -- what an
underwriter concluded -- because HMDA records decisions and never records
whether the loan was repaid. This fits one against a real default outcome on
30,000 credit accounts that also carry sex, education and marital status, which
is the only configuration in which fairness can be measured against REPAYMENT
rather than against a past decision.

Writes docs/REPAYMENT.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.fair_lending import adverse_impact_ratio
from src.repayment import (DATA, calibration_by_group, calibration_error, load,
                           outcome_rates, undocumented_codes)

FEATURES = ["limit_bal", "age", "utilisation", "worst_delinquency",
            "months_delinquent", "pay_0", "pay_2", "bill_1", "pay_amt_1"]


def main() -> int:
    if not DATA.exists():
        print("data/credit_default.parquet not found -- run fetch_repayment_data.py")
        return 1

    df = load().dropna(subset=FEATURES).copy()
    X = df[FEATURES].to_numpy(float)
    y = df["default"].to_numpy(int)

    # A held-out split, because every calibration figure below is meaningless
    # in-sample: a model is calibrated on the data it was fitted to almost by
    # construction.
    idx = np.arange(len(df))
    tr, te = train_test_split(idx, test_size=0.3, random_state=7, stratify=y)
    mu, sd = X[tr].mean(0), X[tr].std(0)
    sd[sd == 0] = 1.0
    model = LogisticRegression(max_iter=5000).fit((X[tr] - mu) / sd, y[tr])
    p_te = model.predict_proba((X[te] - mu) / sd)[:, 1]
    test = df.iloc[te].copy()
    auc = roc_auc_score(y[te], p_te)

    L = []
    add = L.append
    add("# ML-3 — a scorecard fitted on repayment, not on a decision")
    add("")
    add("Generated by `run_repayment.py` on {:,} real credit accounts".format(len(df)))
    add("(UCI/OpenML default-of-credit-card-clients: Taiwan, 2005, six months of")
    add("repayment history and a binary default outcome for the following")
    add("month). Held-out test set of {:,}.".format(len(te)))
    add("")

    add("## Why a second dataset at all")
    add("")
    add("| | target | what a card fitted on it learns |")
    add("|---|---|---|")
    add("| HMDA | `denied` — what an underwriter concluded | to imitate the underwriter, including their mistakes |")
    add("| this | `default` — what the borrower subsequently did | credit risk |")
    add("")
    add("HMDA records decisions and never records repayment. Every AUC, KS and")
    add("PSI figure computed on it in this project is a statement about")
    add("agreement with past decisions, and `docs/HMDA_FAIR_LENDING.md` says so.")
    add("`run_overrides.py` put the same gap the other way round: *the two")
    add("halves of the question live in two datasets and no public source joins")
    add("them.*")
    add("")
    add("**Freddie Mac was tried first.** Its Single-Family Loan-Level dataset")
    add("is free, carries real repayment outcomes, and requires registering an")
    add("account — which is not something to do on somebody's behalf. It also")
    add("contains only originated loans, so it carries an outcome and no")
    add("protected attributes.")
    add("")
    add("This file carries **both in the same place**, which is the only")
    add("configuration in which a fairness metric can be computed against")
    add("repayment. It is Taiwanese revolving credit in 2005, not US mortgages")
    add("in 2023: nothing measured here transfers to the HMDA population, and")
    add("the two are kept in separate documents for that reason.")
    add("")

    add("## The column mapping was verified, not assumed")
    add("")
    add("The file arrives with columns named `x1`..`x23`, `y`. The published")
    add("dictionary gives a mapping and this checks it against the data before")
    add("relying on it: `x1` spans 10,000–1,000,000 across 81 values (a credit")
    add("limit), `x2` is binary, `x5` runs 21–79 (an age), `x6` runs −2..8 (a")
    add("repayment status), `x12` goes negative (a bill amount) — and the")
    add("resulting default rate is **{:.2%}**, which matches the published".format(
        df["default"].mean()))
    add("figure for this study exactly. That match is what confirms the mapping.")
    add("")

    add("## Undocumented codes")
    add("")
    und = undocumented_codes(df)
    add("The dictionary says EDUCATION takes 1–4 and MARRIAGE 1–3. The file")
    add("disagrees:")
    add("")
    add("| column | level | accounts | share | default rate |")
    add("|---|---|---|---|---|")
    for _, r in und.iterrows():
        add("| `{}` | {} | {:,} | {:.2%} | {:.2%} |".format(
            r["column"], r["level"], int(r["n"]), r["share"], r["default_rate"]))
    add("")
    add("Kept as their own levels rather than folded into *other*. A code nobody")
    add("documented is a fact about the data-collection process, and folding it")
    add("away destroys the only evidence that it happened — which is exactly the")
    add("case `src/categorical.py` was written for. Note their default rates:")
    add("they are not interchangeable with each other or with `other`.")
    add("")

    add("## The model")
    add("")
    add("| | |")
    add("|---|---|")
    add("| features | {} |".format(", ".join("`{}`".format(f) for f in FEATURES)))
    add("| test AUC | **{:.4f}** |".format(auc))
    add("| base default rate | {:.2%} |".format(df["default"].mean()))
    add("")
    hmda_auc = 0.7550
    add("### The comparison that inverted")
    add("")
    add("This document first asserted that the HMDA stand-in model scored 0.66")
    add("and that a real-outcome model would beat it. Checking")
    add("`docs/OVERRIDES.md` rather than remembering it: the HMDA model scores")
    add("**{:.4f}**, and this one scores **{:.4f}**. The decision model is".format(
        hmda_auc, auc))
    add("*better*.")
    add("")
    add("Which is the more interesting result, and it argues for this dataset")
    add("rather than against it. **Predicting a decision is an easier problem")
    add("than predicting default.** An underwriter's decision is a largely")
    add("deterministic function of the application in front of them, so a model")
    add("fitted to it is reverse-engineering a rule. Default is genuinely")
    add("uncertain: the same applicant repays or does not, and no feature set")
    add("resolves that.")
    add("")
    add("So a high AUC against `denied` is not evidence of a good credit model.")
    add("It is evidence that the target was easy — and the easier the target,")
    add("the more completely the model has learned to imitate the underwriter")
    add("rather than the risk. **Comparing the two AUCs as though they measured")
    add("the same thing is the error**, and this document made it before it")
    add("looked the number up.")
    add("")

    add("## The question a decision target cannot pose")
    add("")
    add("With a decision target you can measure whether groups are treated")
    add("differently. You cannot measure whether they are treated **correctly**,")
    add("because there is nothing to be correct about — the target *is* the")
    add("treatment. A real outcome separates the two:")
    add("")
    add("### Disparity: does the model decline one group more?")
    add("")
    cutoff = float(np.quantile(p_te, 0.80))
    approved = (p_te < cutoff)
    for by in ("sex_label", "education_label"):
        groups = test[by].to_numpy()
        rates = outcome_rates(test.assign(_a=approved), by)
        appr = test.assign(_a=approved).groupby(by)._a.mean()
        add("")
        add("**by `{}`** (approving the safest 80% by predicted PD)".format(by))
        add("")
        add("| group | accounts | approval rate | **actual default rate** |")
        add("|---|---|---|---|")
        for _, r in rates.iterrows():
            if r["n"] < 200:
                continue
            add("| {} | {:,} | {:.2%} | **{:.2%}** |".format(
                r[by], int(r["n"]), appr[r[by]], r["default_rate"]))
    add("")

    binary = test[test.sex_label.isin(["male", "female"])]
    b_appr = approved[test.sex_label.isin(["male", "female"]).to_numpy()]
    air = adverse_impact_ratio(b_appr, (binary.sex_label == "male").to_numpy().astype(int))
    add("Adverse impact ratio on sex: **{:.4f}**".format(air["air"]))
    add("")
    m = test[test.sex_label == "male"]["default"].mean()
    f = test[test.sex_label == "female"]["default"].mean()
    add("And the actual default rates are {:.2%} for men against {:.2%} for".format(m, f))
    add("women — a real difference of **{:.2f} percentage points**, in the".format(
        (m - f) * 100))
    add("data rather than in the model.")
    add("")

    add("### Calibration: is the probability it assigns them right for them?")
    add("")
    cal = calibration_by_group(binary, p_te[test.sex_label.isin(
        ["male", "female"]).to_numpy()], "sex_label")
    err = calibration_error(cal, "sex_label")
    add("| group | accounts | weighted abs. gap | signed gap |")
    add("|---|---|---|---|")
    for _, r in err.iterrows():
        add("| {} | {:,} | {:.4f} | {:+.4f} |".format(
            r["sex_label"], int(r["n"]), r["weighted_abs_gap"], r["signed_gap"]))
    add("")
    add("Measured **out of sample**, because a model is calibrated on its own")
    add("training data almost by construction and an in-sample calibration")
    add("figure is a statement about fitting rather than about fairness.")
    add("")
    worst = err.sort_values("weighted_abs_gap").iloc[-1]
    best = err.sort_values("weighted_abs_gap").iloc[0]
    add("The gap between the best- and worst-calibrated group is")
    add("{:.4f} against {:.4f}.".format(best["weighted_abs_gap"],
                                        worst["weighted_abs_gap"]))
    add("")

    add("### Reading the two together")
    add("")
    add("This is the tension `docs/HMDA_FAIR_LENDING.md` could state and could")
    add("not measure. **If a group genuinely defaults more, a well-calibrated")
    add("model declines them more, and the AIR falls without anything in the")
    add("model being wrong about them.** Equalising the AIR then requires")
    add("lending to the higher-risk group at a price that does not cover their")
    add("risk.")
    add("")
    add("That is a policy choice somebody should make deliberately, not a bug")
    add("to be patched out of a model — and it is only visible at all because")
    add("there is a real outcome to check the model against. On a decision")
    add("target the same two numbers would be the same number.")
    add("")

    add("## What this does not license")
    add("")
    add("- **Nothing here transfers to HMDA.** Taiwanese revolving credit in")
    add("  2005 against US mortgages in 2023. The value is that the target means")
    add("  what the word means, not that the population is comparable.")
    add("- **Calibration is not sufficient either.** A model can be perfectly")
    add("  calibrated within each group and still encode a historical injustice,")
    add("  if the outcome itself was shaped by one. Calibration checks the model")
    add("  against the world as it is; it cannot check the world.")
    add("- **Sex here is binary because the file is.** A two-level protected")
    add("  attribute is the easy case and real fairness work is not that.")
    add("- **No reject inference.** These are all approved accounts, so the")
    add("  default rate is conditioned on someone having already said yes —")
    add("  which is the same selection `src/reject_inference.py` exists for, in")
    add("  a dataset that cannot correct it.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "REPAYMENT.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/REPAYMENT.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
