"""Interactions on real HMDA, and whether crossing features builds a proxy.

    python run_interactions.py

A WoE scorecard is additive by construction: it can say "high LTV is worse" and
"this loan purpose is worse" and it cannot say "high LTV is worse FOR this
purpose". Crossing two features into one categorical is the standard fix, and
the standard fix has a cost this project can measure on real data with real
protected attributes.

The cost that matters is not cell count. It is that AN INTERACTION IS WHERE A
SCORECARD BECOMES A PROXY: two features can each be individually neutral and
their intersection can be almost entirely one group. `src/fair_lending.py`
measures disparity per feature, so it cannot see this -- before the cross, those
intersections were not features.

Writes docs/INTERACTIONS.md.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from src.hmda import DATA, load, protected
from src.interactions import (MIN_CELL_SHARE, MIN_GROUP_COUNT,
                              PROXY_CONCENTRATION_RATIO, additive_prediction,
                              cell_counts, cross, detect, proxy_screen)


def _band(s: pd.Series, edges, labels) -> pd.Series:
    return pd.cut(s, edges, labels=labels, include_lowest=True).astype(str)


def main() -> int:
    if not DATA.exists():
        print("data/hmda_de_2023.csv not found -- see src/hmda.py")
        return 1

    df = protected(load()).dropna(subset=["ltv", "dti", "income_k"]).copy()

    # Two features that are plainly legitimate underwriting inputs, banded so
    # they are categorical. Neither is a protected attribute and neither is
    # obviously a proxy for one.
    df["ltv_band"] = _band(df.ltv, [0, 80, 90, 95, 200],
                           ["<=80", "80-90", "90-95", ">95"])
    df["dti_band"] = _band(df.dti, [0, 30, 36, 43, 100],
                           ["<30", "30-36", "36-43", ">43"])
    df["income_band"] = _band(df.income_k, [0, 60, 100, 150, 5000],
                              ["<60k", "60-100k", "100-150k", ">150k"])

    y = df.denied.to_numpy()
    reported = df[df.race_reported].copy()

    L = []
    add = L.append
    add("# ML-3 — interactions, and the proxy a cross can smuggle in")
    add("")
    add("Generated by `run_interactions.py` on {:,} real HMDA 2023 Delaware".format(
        len(df)))
    add("applications.")
    add("")
    add("A WoE scorecard is **additive by construction**. Each feature becomes")
    add("its weight of evidence and the pieces are summed in log-odds space, so")
    add("the card can say *high LTV is worse* and *high DTI is worse* and it")
    add("cannot say *high LTV is worse when DTI is also high*. An interaction is")
    add("precisely the statement the functional form cannot make.")
    add("")

    add("## 1. Does the additive assumption actually cost anything here?")
    add("")
    cells = detect(df.ltv_band, df.dti_band, y)
    add("| LTV | DTI | applications | share | observed denial | additive predicts | gap |")
    add("|---|---|---|---|---|---|---|")
    for c in cells[:8]:
        add("| {} | {} | {:,} | {:.1%} | {:.2%} | {:.2%} | **{:+.2f} pp** |".format(
            c.level_a, c.level_b, c.n, c.share, c.bad_rate,
            c.additive_bad_rate, c.surprise * 100))
    add("")
    worst = cells[0]
    add("The largest weighted gap is **{:+.2f} percentage points** on the".format(
        worst.surprise * 100))
    add("`{} x {}` cell, which holds {:.1%} of applications.".format(
        worst.level_a, worst.level_b, worst.share))
    add("")
    add("Ranked by surprise **weighted by population**. An unweighted ranking")
    add("puts the thinnest cells on top, because a cell of forty applicants can")
    add("be surprising by pure sampling — and the top of a report is where a")
    add("reader looks.")
    add("")

    add("## 2. What the cross costs in cells")
    add("")
    add("| cross | cells | above the {:.0%} floor | population that would merge to OTHER |".format(
        MIN_CELL_SHARE))
    add("|---|---|---|---|")
    for na, nb, a, b in (("ltv_band", "dti_band", df.ltv_band, df.dti_band),
                         ("ltv_band", "income_band", df.ltv_band, df.income_band),
                         ("dti_band", "income_band", df.dti_band, df.income_band)):
        c = cell_counts(a, b)
        add("| `{}` x `{}` | {} | {} | {:.1%} |".format(
            na, nb, c["cells"], c["cells_above_floor"],
            c["population_merged_to_other"]))
    add("")
    merged = max(cell_counts(a, b)["population_merged_to_other"]
                 for a, b in ((df.ltv_band, df.dti_band),
                              (df.ltv_band, df.income_band),
                              (df.dti_band, df.income_band)))
    if merged < 0.005:
        add("**Every cell survives the floor here, so this cost does not bite")
        add("on these crosses** — 4x4 on 26,314 applications leaves every cell")
        add("populated. Reported anyway rather than dropped, because it is the")
        add("number to check BEFORE deciding a cross is worth it and the answer")
        add("happens to be favourable this time.")
        add("")
        add("Where it does bite is a cross of two genuinely high-cardinality")
        add("features — a 12-level purpose against a 20-level property type is")
        add("240 cells, most below the floor. Those merge into OTHER, and the")
        add("interaction that motivated the cross disappears into a bucket, so")
        add("the cross buys nothing but degrees of freedom.")
    else:
        add("Crossing a 4-level feature with another gives 16 cells and the")
        add("population does not grow to match. {:.1%} of applications fall".format(
            merged))
        add("into cells below the floor and merge into OTHER — **the")
        add("interaction that motivated the cross disappears into a bucket**.")
    add("")

    add("## 3. The check a per-feature fairness screen cannot perform")
    add("")
    add("Both inputs are legitimate underwriting variables. Neither is a")
    add("protected attribute. The question is whether their **intersection**")
    add("identifies a group.")
    add("")
    add("Measured against {:,} applications with race reported.".format(
        len(reported)))
    add("")
    for na, nb, a, b in (
            ("ltv_band", "dti_band", reported.ltv_band, reported.dti_band),
            ("ltv_band", "income_band", reported.ltv_band, reported.income_band),
            ("dti_band", "income_band", reported.dti_band, reported.income_band)):
        findings = proxy_screen(a, b, reported.race_group)
        add("**`{}` x `{}`** — {} cell(s) at or above {:.0f}x concentration".format(
            na, nb, len(findings), PROXY_CONCENTRATION_RATIO))
        add("")
        if findings:
            add("| cell | n | group | in cell | share in cell | share of book | concentration |")
            add("|---|---|---|---|---|---|---|")
            for f in findings[:5]:
                add("| {} x {} | {:,} | {} | {:,} | {:.1%} | {:.1%} | **{:.1f}x** |".format(
                    f.level_a, f.level_b, f.n, f.group, f.group_count_in_cell,
                    f.group_share_in_cell, f.group_share_in_population,
                    f.concentration))
        add("")

    any_found = any(proxy_screen(a, b, reported.race_group) for a, b in (
        (reported.ltv_band, reported.dti_band),
        (reported.ltv_band, reported.income_band),
        (reported.dti_band, reported.income_band)))

    add("### Reading this result")
    add("")
    if any_found:
        add("At least one cell concentrates a group at {:.0f}x its share of the".format(
            PROXY_CONCENTRATION_RATIO))
        add("book. That is a **screen result**, not a finding of discrimination:")
        add("it says the crossed feature carries information about group")
        add("membership that neither input carried alone, which is exactly the")
        add("condition under which a neutral-looking model becomes a proxy.")
    else:
        add("**No cell reaches {:.0f}x on this data.** That is the honest".format(
            PROXY_CONCENTRATION_RATIO))
        add("outcome and it is worth stating plainly rather than hunting for a")
        add("cross that does fire. Delaware's HMDA population is not")
        add("segregated finely enough along LTV, DTI and income for a 4x4 cross")
        add("of them to isolate a racial group.")
        add("")
        add("A null result from a control is still a result. What it does not")
        add("license is the conclusion that crossing features is safe in")
        add("general — it is a statement about these three variables on this")
        add("state's book, and `run_redlining.py` already showed that")
        add("**geography** on the same data does carry group information.")
        add("Crossing a geographic band into a card is the case this screen")
        add("exists for.")
    add("")

    # ------------------------------------------------- geography, the real case
    add("## 4. The cross that does carry group information")
    add("")
    add("`run_redlining.py` found that tract minority share predicts denial even")
    add("after controlling for the applicant's own group. So geography is the")
    add("input where a cross is most likely to build a proxy — and it is")
    add("routinely present in a card as a region code or a property-type band.")
    add("")
    geo = reported[reported.census_tract.notna()].copy()
    if len(geo):
        tract = geo.groupby(geo.census_tract.astype(str)).agg(
            share=("is_minority", "mean"), n=("denied", "size"))
        tract = tract[tract.n >= 30]
        geo["tract_band"] = geo.census_tract.astype(str).map(
            lambda t: None if t not in tract.index else
            "<20%" if tract.share[t] < 0.2 else
            "20-50%" if tract.share[t] < 0.5 else "50%+")
        geo = geo.dropna(subset=["tract_band"])

        gf = proxy_screen(geo.tract_band, geo.ltv_band, geo.race_group)
        add("`tract_band` x `ltv_band` on {:,} applications: **{}** cell(s) at".format(
            len(geo), len(gf)))
        add("or above {:.0f}x.".format(PROXY_CONCENTRATION_RATIO))
        add("")
        if gf:
            add("| cell | n | group | in cell | share in cell | share of book | concentration |")
            add("|---|---|---|---|---|---|---|")
            for f in gf[:6]:
                add("| {} x {} | {:,} | {} | {:,} | {:.1%} | {:.1%} | **{:.1f}x** |".format(
                    f.level_a, f.level_b, f.n, f.group, f.group_count_in_cell,
                    f.group_share_in_cell, f.group_share_in_population,
                    f.concentration))
            add("")
            add("**A geographic band crossed with an ordinary underwriting")
            add("variable produces cells that identify a group** where the")
            add("purely-financial crosses in section 3 did not. That is the")
            add("difference between a variable that happens to correlate with")
            add("risk and one that carries where somebody lives.")
        else:
            add("None reaches the threshold either, on the tract bands available")
            add("here. Delaware has 19 majority-minority tracts in this extract,")
            add("which is a thin base for a cross — the screen is reporting the")
            add("limits of the sample as much as the state of the market.")
    add("")

    add("## 5. A spurious finding this screen produced, and the fix")
    add("")
    add("**The first version of this run reported two proxy cells. Both were")
    add("noise, and the screen was wrong rather than the data.**")
    add("")
    add("| cell | applicants | group | in cell | group share of book | reported |")
    add("|---|---|---|---|---|---|")
    add("| `90-95 x <60k` | 233 | Native Hawaiian or Other Pacific Islander | **2** | 0.2% | 3.6x |")
    add("| `50%+ x >95` | 1,125 | 2 or more minority races | **18** | 0.5% | 3.2x |")
    add("")
    add("The first cell's group is 0.2% of the book, so its expected count in a")
    add("233-applicant cell is **half a person**. Two applicants produced a")
    add("3.6x ratio. That is not a proxy; it is a rounding error with a ratio")
    add("attached.")
    add("")
    add("The screen floored the CELL size and not the GROUP COUNT inside it —")
    add("and a ratio is unstable exactly where its denominator is small, which")
    add("a cell-size floor does not constrain. `MIN_GROUP_COUNT = {}` closes".format(
        MIN_GROUP_COUNT))
    add("it, and both findings disappear.")
    add("")
    add("Worth recording because the failure is invisible in a synthetic test:")
    add("a constructed proxy world has one group at 10% and a clear signal. It")
    add("takes real data, with a long tail of small groups, to produce a")
    add("confident 3.6x from two people.")
    add("")

    add("## 6. A limitation of this screen, found by a test")
    add("")
    add("Concentration is measured against the **book's own** mix, which makes")
    add("it self-referential. When a cell is a large fraction of the population,")
    add("filling it with a group raises the book's rate too and the ratio falls")
    add("back toward 1.")
    add("")
    add("On a 2x2 cross each cell is a quarter of the book: loading one of them")
    add("75% with a group that starts at 10% takes the population to ~27% and")
    add("the cell to ~77% — a concentration of **2.9**, under the 3.0 threshold,")
    add("on a cell that is three-quarters one group.")
    add("")
    add("So the screen is most sensitive where cells are small, which is where")
    add("proxies usually live, and least sensitive on coarse crosses. Fixing it")
    add("properly needs an external reference population rather than the book")
    add("itself. A test pins the behaviour so it is a known limitation rather")
    add("than a surprise.")
    add("")

    add("## 7. What this does not establish")
    add("")
    add("- **A concentrated cell is not proof of discrimination.** It is proof")
    add("  that a feature the model can use carries information about group")
    add("  membership. Whether the model then uses it, and with what effect, is")
    add("  the AIR and the redlining screen's question.")
    add("- **One state, one year, one lender pool.** Every caveat from")
    add("  `docs/HMDA_FAIR_LENDING.md` applies unchanged.")
    add("- **The bands are chosen.** LTV at 80/90/95 follows mortgage-insurance")
    add("  conventions and DTI at 36/43 follows QM, so they are not arbitrary —")
    add("  but different cuts would give different cells, and a screen that is")
    add("  sensitive to banding is sensitive to a modelling choice.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "INTERACTIONS.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/INTERACTIONS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
