"""Fair-lending analysis for a credit model.

Credit is not fraud, and the regulatory frame is different in ways that change
what has to be computed:

  ECOA / Regulation B (15 U.S.C. 1691, 12 CFR 1002) governs discrimination in
  credit. Reg B 1002.9 requires an adverse-action notice stating the PRINCIPAL
  REASONS for a denial -- which is why the scorecard's points-lost reason codes
  are a regulatory artifact, not a nice-to-have.

  Disparate TREATMENT: using a prohibited basis (race, sex, national origin,
  age, marital status, receipt of public assistance) as an input, or treating
  applicants differently because of it. A facially discriminatory practice.

  Disparate IMPACT: a facially neutral policy that disproportionately burdens a
  protected class and is not justified by business necessity -- and, even where
  it is, remains actionable if a less discriminatory alternative achieves the
  same business purpose. That last clause is the one most portfolios omit, and
  it is why `less_discriminatory_alternative_search` exists in this module.

The overlay used here is SYNTHETIC. It is generated by `src/generate.py` as
`protected_group_synthetic`, correlated with `region_risk` by construction so
that a genuine proxy structure exists to detect. No result in this module
describes any real population, and the README says so before it says anything
else.
"""
from __future__ import annotations

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score

AIR_THRESHOLD = 0.80


def adverse_impact_ratio(approved: np.ndarray, group: np.ndarray) -> dict:
    r1 = float(approved[group == 1].mean())
    r0 = float(approved[group == 0].mean())
    lo, hi = min(r1, r0), max(r1, r0)
    air = lo / hi if hi else float("nan")
    return {"rate_1": r1, "rate_0": r0, "air": air,
            "flags": bool(air < AIR_THRESHOLD),
            "disadvantaged": 1 if r1 < r0 else 0}


def air_confidence_interval(approved: np.ndarray, group: np.ndarray,
                            n_boot: int = 400, seed: int = 3) -> tuple[float, float]:
    """Bootstrap CI on the AIR.

    A point-estimate AIR of 0.79 on a thin sample is not the same finding as
    0.79 on a fat one, and the 80% rule is applied to the estimate as if it
    were exact. Reporting the interval is the difference between a screen and a
    number that gets quoted in a memo.
    """
    rng = np.random.default_rng(seed)
    n = len(approved)
    vals = []
    for _ in range(n_boot):
        idx = rng.integers(0, n, n)
        g, a = group[idx], approved[idx]
        if (g == 1).sum() < 10 or (g == 0).sum() < 10:
            continue
        vals.append(adverse_impact_ratio(a, g)["air"])
    if not vals:
        return (float("nan"), float("nan"))
    return (float(np.quantile(vals, 0.025)), float(np.quantile(vals, 0.975)))


def score_distribution(score: np.ndarray, group: np.ndarray) -> dict:
    a, b = score[group == 1], score[group == 0]
    return {
        "mean_1": float(a.mean()), "mean_0": float(b.mean()),
        "median_1": float(np.median(a)), "median_0": float(np.median(b)),
        "p10_1": float(np.quantile(a, 0.10)), "p10_0": float(np.quantile(b, 0.10)),
        "mean_gap_points": float(a.mean() - b.mean()),
        "separation_auc": float(roc_auc_score(group, -score)),
    }


def proxy_reconstruction(X: np.ndarray, group: np.ndarray) -> float:
    """How well do the model's own features predict group membership?

    This is the number that tells you whether 'we don't use the attribute' means
    anything. AUC 0.5 means the features carry no group information; well above
    that means the model can act on the attribute without ever seeing it.
    """
    Xs = (X - X.mean(axis=0)) / (X.std(axis=0) + 1e-9)
    probe = LogisticRegression(max_iter=1000)
    probe.fit(Xs, group)
    return float(roc_auc_score(group, probe.predict_proba(Xs)[:, 1]))


def proxy_ablation(fit_predict, X_tr, y_tr, X_te, feature_names: list[str],
                   group_te: np.ndarray, drop: list[str],
                   approval_rate: float) -> dict:
    """Refit without the suspected proxies; re-measure disparity AND reconstruction.

    `fit_predict(X_tr, y_tr, X_te, names) -> scores_te` keeps this agnostic to
    whether the model is a scorecard or a GBM. `names` is passed explicitly
    because the ablated call hands over FEWER columns, and a callback that
    assumed the full feature list would silently index off the end.

    The result to watch for is the uncomfortable one: reconstruction AUC falls
    (the dropped columns did carry group information) while the AIR does not move
    (the disparity was never coming from those columns alone). Dropping features
    is then a cosmetic change that costs accuracy and buys no fairness -- and
    telling that story requires measuring both quantities, which is why this
    returns both.
    """
    keep = [i for i, f in enumerate(feature_names) if f not in drop]

    kept_names = [feature_names[i] for i in keep]
    s_full = fit_predict(X_tr, y_tr, X_te, feature_names)
    thr_full = float(np.quantile(s_full, approval_rate))
    air_full = adverse_impact_ratio(s_full <= thr_full, group_te)

    s_abl = fit_predict(X_tr[:, keep], y_tr, X_te[:, keep], kept_names)
    thr_abl = float(np.quantile(s_abl, approval_rate))
    air_abl = adverse_impact_ratio(s_abl <= thr_abl, group_te)

    recon_full = proxy_reconstruction(X_te, group_te)
    recon_abl = proxy_reconstruction(X_te[:, keep], group_te)
    lift_full = max(recon_full - 0.5, 1e-9)
    lift_abl = max(recon_abl - 0.5, 0.0)

    return {
        "dropped": drop,
        "air_full": air_full["air"], "air_ablated": air_abl["air"],
        "air_change": air_abl["air"] - air_full["air"],
        "recon_full": recon_full, "recon_ablated": recon_abl,
        "signal_retained": lift_abl / lift_full,
        "scores_full": s_full, "scores_ablated": s_abl,
    }


def less_discriminatory_alternative_search(candidates: dict[str, dict]) -> dict:
    """The clause most fair-lending sections omit.

    Under disparate-impact doctrine, showing business necessity is not the end of
    the analysis: if a less discriminatory alternative serves the same business
    purpose comparably well, the original practice remains actionable.

    `candidates` maps name -> {"air": float, "auc": float}. An alternative
    qualifies if it improves AIR materially while giving up little discrimination.
    The tolerance below is a policy choice and is stated rather than buried:
    up to 0.005 AUC (0.01 Gini) may be surrendered for a >= 0.02 AIR gain.
    """
    AUC_TOLERANCE = 0.005
    AIR_MIN_GAIN = 0.02

    base = candidates.get("champion")
    if base is None:
        raise ValueError("candidates must include a 'champion' entry")

    qualifying, assessed = [], []
    for name, c in candidates.items():
        if name == "champion":
            continue
        air_gain = c["air"] - base["air"]
        auc_cost = base["auc"] - c["auc"]
        helps = air_gain >= AIR_MIN_GAIN
        affordable = auc_cost <= AUC_TOLERANCE
        # The two failure modes are recorded separately because they mean
        # entirely different things to a reviewer. "Did not reduce disparity" is
        # the end of the enquiry. "Reduced disparity but cost too much
        # discrimination" is NOT -- it is a live question about whether the
        # tolerance itself is defensible, and burying it inside a single
        # pass/fail verdict is how a real alternative gets quietly dismissed.
        verdict = ("qualifies" if helps and affordable else
                   "reduces disparity but exceeds the accuracy tolerance"
                   if helps and not affordable else
                   "does not reduce disparity materially")
        assessed.append({"name": name, "air_gain": air_gain,
                         "auc_cost": auc_cost, "verdict": verdict})
        if helps and affordable:
            qualifying.append({"name": name, "air_gain": air_gain,
                               "auc_cost": auc_cost})
    blocked_on_cost = [a for a in assessed
                       if a["verdict"].startswith("reduces disparity")]
    return {
        "champion_air": base["air"], "champion_auc": base["auc"],
        "auc_tolerance": AUC_TOLERANCE, "air_min_gain": AIR_MIN_GAIN,
        "qualifying_alternatives": sorted(qualifying, key=lambda d: -d["air_gain"]),
        "assessed": assessed,
        "blocked_on_cost": blocked_on_cost,
        "conclusion": (
            "a less discriminatory alternative was identified and must be considered"
            if qualifying else
            "an alternative DID reduce disparity but exceeded the stated accuracy "
            "tolerance -- the tolerance itself now requires justification, and this "
            "is not a clean pass"
            if blocked_on_cost else
            "no candidate reduced disparity by the required margin"),
    }
